
package fr.afcepf.al28.jeeapp.ejb.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import fr.afcepf.al28.jeeapp.ejb.itf.DeviseDto;
import fr.afcepf.al28.jeeapp.ejb.itf.ObjectFactory;
import fr.afcepf.al28.jeeapp.ejb.itf.PaysDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceDevise", targetNamespace = "http://itf.ejb.jeeapp.al28.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceDevise {


    /**
     * 
     * @param codeDevise
     * @return
     *     returns java.util.List<fr.afcepf.al28.jeeapp.ejb.itf.PaysDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListPaysPartageantDevise", targetNamespace = "http://itf.ejb.jeeapp.al28.afcepf.fr/", className = "fr.afcepf.al28.jeeapp.ejb.itf.GetListPaysPartageantDevise")
    @ResponseWrapper(localName = "getListPaysPartageantDeviseResponse", targetNamespace = "http://itf.ejb.jeeapp.al28.afcepf.fr/", className = "fr.afcepf.al28.jeeapp.ejb.itf.GetListPaysPartageantDeviseResponse")
    public List<PaysDto> getListPaysPartageantDevise(
        @WebParam(name = "codeDevise", targetNamespace = "")
        String codeDevise);

    /**
     * 
     * @return
     *     returns java.util.List<fr.afcepf.al28.jeeapp.ejb.itf.DeviseDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toutesDevises", targetNamespace = "http://itf.ejb.jeeapp.al28.afcepf.fr/", className = "fr.afcepf.al28.jeeapp.ejb.itf.ToutesDevises")
    @ResponseWrapper(localName = "toutesDevisesResponse", targetNamespace = "http://itf.ejb.jeeapp.al28.afcepf.fr/", className = "fr.afcepf.al28.jeeapp.ejb.itf.ToutesDevisesResponse")
    public List<DeviseDto> toutesDevises();

    /**
     * 
     * @param devSource
     * @param devCible
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertir", targetNamespace = "http://itf.ejb.jeeapp.al28.afcepf.fr/", className = "fr.afcepf.al28.jeeapp.ejb.itf.Convertir")
    @ResponseWrapper(localName = "convertirResponse", targetNamespace = "http://itf.ejb.jeeapp.al28.afcepf.fr/", className = "fr.afcepf.al28.jeeapp.ejb.itf.ConvertirResponse")
    public double convertir(
        @WebParam(name = "montant", targetNamespace = "")
        double montant,
        @WebParam(name = "devSource", targetNamespace = "")
        String devSource,
        @WebParam(name = "devCible", targetNamespace = "")
        String devCible);

    /**
     * 
     * @param codeDevise
     * @return
     *     returns fr.afcepf.al28.jeeapp.ejb.itf.DeviseDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherDevise", targetNamespace = "http://itf.ejb.jeeapp.al28.afcepf.fr/", className = "fr.afcepf.al28.jeeapp.ejb.itf.RechercherDevise")
    @ResponseWrapper(localName = "rechercherDeviseResponse", targetNamespace = "http://itf.ejb.jeeapp.al28.afcepf.fr/", className = "fr.afcepf.al28.jeeapp.ejb.itf.RechercherDeviseResponse")
    public DeviseDto rechercherDevise(
        @WebParam(name = "codeDevise", targetNamespace = "")
        String codeDevise);

}
